import {WeaponManager,WEAPONS} from './weapons.js';
import {EnemyManager} from './enemies.js';

export class Game{
 constructor(canvas){this.c=canvas;this.ctx=canvas.getContext('2d');this.w=1280;this.h=720;this.angle=0;this.hp=100;this.wave=1;this.weapons=new WeaponManager();this.enemies=new EnemyManager();this.last=performance.now();this.dragX=null;this.bind();requestAnimationFrame(t=>this.loop(t))}
 bind(){window.addEventListener('keydown',e=>{if(e.key>='1'&&e.key<='4')this.select(+e.key-1);if(e.key==='a'||e.key==='ArrowLeft')this.angle=Math.max(-90,this.angle-5);if(e.key==='d'||e.key==='ArrowRight')this.angle=Math.min(90,this.angle+5)});this.c.addEventListener('pointerdown',e=>{this.dragX=e.clientX;this.fire()});window.addEventListener('pointerup',()=>this.dragX=null);window.addEventListener('pointermove',e=>{if(this.dragX!==null){const dx=e.clientX-this.dragX;this.angle=Math.max(-90,Math.min(90,this.angle+dx*.12));this.dragX=e.clientX}})}
 select(i){this.weapons.select(i);this.updateWeaponUI()}
 fire(){const now=performance.now();if(!this.weapons.shoot(now))return;const weapon=this.weapons.current;let candidates=this.enemies.enemies.filter(e=>Math.abs(e.x)<weapon.range&&e.y<weapon.range);candidates.sort((a,b)=>b.y-a.y);if(candidates[0])candidates[0].hit(weapon.damage)}
 update(dt){this.enemies.update(dt);this.enemies.enemies.forEach(e=>{if(e.y>550)this.hp=Math.max(0,this.hp-dt*4)})}
 loop(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.update(dt);this.render();requestAnimationFrame(x=>this.loop(x))}
 render(){const c=this.ctx;c.clearRect(0,0,this.w,this.h);this.drawSky(c);this.drawField(c);this.drawTower(c);this.drawEnemies(c);this.drawWeapon(c);this.updateUI()}
 drawSky(c){const g=c.createLinearGradient(0,0,0,430);g.addColorStop(0,'#7697b8');g.addColorStop(1,'#d8c8a7');c.fillStyle=g;c.fillRect(0,0,this.w,430);c.fillStyle='rgba(255,255,255,.35)';c.beginPath();c.arc(1030,115,45,0,Math.PI*2);c.fill();for(let i=0;i<7;i++){c.fillStyle='#6c7d73';c.beginPath();c.moveTo(i*220-100,360);c.lineTo(i*220+40,190+(i%3)*35);c.lineTo(i*220+210,360);c.fill()}}
 drawField(c){c.fillStyle='#5e6b49';c.fillRect(0,350,1280,370);c.fillStyle='#ad9369';c.beginPath();c.moveTo(520,720);c.lineTo(760,720);c.lineTo(670,360);c.lineTo(610,360);c.closePath();c.fill();c.strokeStyle='#7b6548';c.lineWidth=3;for(let y=400;y<700;y+=55){const p=(y-360)/360;c.beginPath();c.moveTo(610-p*80,y);c.lineTo(670+p*80,y);c.stroke()}}
 drawTower(c){c.fillStyle='#272b2e';c.fillRect(0,610,1280,110);c.fillStyle='#4d4a43';for(let x=0;x<1280;x+=110)c.fillRect(x,580,70,75);c.fillStyle='#34383a';c.fillRect(0,650,1280,70);c.fillStyle='#7d776a';for(let x=20;x<1280;x+=130)c.fillRect(x,630,85,12)}
 drawEnemies(c){for(const e of this.enemies.enemies){const depth=Math.max(0,Math.min(1,(e.y+30)/610));const scale=.45+depth*.9;const sx=640+e.x*(.5+depth);const sy=360+depth*260;const r=e.radius*scale;c.fillStyle='#79b86b';c.beginPath();c.ellipse(sx,sy,r,r*.75,0,0,Math.PI*2);c.fill();c.fillStyle='#26351f';c.beginPath();c.arc(sx-r*.3,sy-r*.1,2.5*scale,0,Math.PI*2);c.arc(sx+r*.3,sy-r*.1,2.5*scale,0,Math.PI*2);c.fill();c.fillStyle='#24272a';c.fillRect(sx-r,sy-r-10,r*2,4);c.fillStyle='#d75c57';c.fillRect(sx-r,sy-r-10,r*2*(e.hp/e.maxHp),4)}}
 drawWeapon(c){const w=this.weapons.current.id;c.save();c.translate(860,580);c.rotate(-.12);c.fillStyle='#1c1b1a';c.fillRect(30,0,260,30);c.fillStyle='#6b4630';c.fillRect(170,-55,45,150);c.fillStyle='#b98a58';c.fillRect(0,-15,75,12);if(w==='bow'){c.strokeStyle='#1e1a16';c.lineWidth=7;c.beginPath();c.arc(0,0,95,-1.15,1.15);c.stroke();c.strokeStyle='#d8c39c';c.lineWidth=2;c.beginPath();c.moveTo(-42,-84);c.lineTo(-42,84);c.stroke()}else if(w.includes('crossbow')){c.fillStyle='#805738';c.fillRect(-30,-10,145,20);c.fillStyle='#252525';c.fillRect(15,-50,10,100);c.fillRect(80,-50,10,100)}else{c.fillStyle='#858585';c.beginPath();c.arc(25,0,34,0,Math.PI*2);c.fill()}c.restore()}
 updateUI(){document.querySelector('#angle').textContent=Math.round(this.angle)+'°';document.querySelector('#enemyCount').textContent=this.enemies.enemies.length;document.querySelector('#towerHp').style.width=this.hp+'%';document.querySelector('.top-left small').textContent=`Tower HP ${Math.ceil(this.hp)} / 100`;this.updateWeaponUI()}
 updateWeaponUI(){const bar=document.querySelector('#weaponBar');bar.innerHTML=WEAPONS.map((w,i)=>`<button class="weapon-slot ${i===this.weapons.index?'active':''}" data-index="${i}"><b>${i+1} · ${w.name}</b><small>${w.range} range · ${w.ammo===Infinity?'∞':this.weapons.ammo[i]+' ammo'}</small></button>`).join('');bar.querySelectorAll('button').forEach(b=>b.onclick=()=>this.select(+b.dataset.index))}
}
