import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {WeaponManager,WEAPONS} from './weapons.js';
import {EnemyManager} from './enemies.js';

export class Game{
 constructor(canvas){
  this.c=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});
  this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));this.renderer.setSize(1280,720,false);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x9eb8cf);this.scene.fog=new THREE.Fog(0x9eb8cf,55,150);
  this.camera=new THREE.PerspectiveCamera(62,16/9,.1,220);this.camera.position.set(0,4.2,10);this.camera.rotation.order='YXZ';
  this.yaw=0;this.pitch=-.08;this.hp=100;this.wave=1;this.weapons=new WeaponManager();this.enemies=new EnemyManager();this.enemyMeshes=new Map();this.projectiles=[];this.last=performance.now();this.pointer={down:false,x:0,y:0,startX:0,startY:0,moved:false};
  this.buildWorld();this.buildWeapon();this.bind();this.resize();window.addEventListener('resize',()=>this.resize());this.updateWeaponUI();requestAnimationFrame(t=>this.loop(t));
 }
 buildWorld(){
  const hemi=new THREE.HemisphereLight(0xdbeeff,0x39442e,2.1);this.scene.add(hemi);
  const sun=new THREE.DirectionalLight(0xffe7bd,3);sun.position.set(-30,45,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);this.scene.add(sun);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x58734b,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.z=-35;ground.receiveShadow=true;this.scene.add(ground);
  const road=new THREE.Mesh(new THREE.PlaneGeometry(12,100),new THREE.MeshStandardMaterial({color:0xb29369,roughness:1}));road.rotation.x=-Math.PI/2;road.position.set(0,.012,-38);road.receiveShadow=true;this.scene.add(road);
  for(let z=-85;z<8;z+=8){const mark=new THREE.Mesh(new THREE.BoxGeometry(5,.035,.16),new THREE.MeshStandardMaterial({color:0x7a6348}));mark.position.set(0,.035,z);this.scene.add(mark)}
  for(let i=0;i<32;i++){const x=(Math.random()-.5)*70;const z=-15-Math.random()*80;const tree=this.makeTree(.7+Math.random()*.7);tree.position.set(x,0,z);this.scene.add(tree)}
  for(const side of [-1,1]){for(let z=-72;z<4;z+=18){const wall=new THREE.Mesh(new THREE.BoxGeometry(3,1.5,4),new THREE.MeshStandardMaterial({color:0x77736a,roughness:.9}));wall.position.set(side*10,.75,z);wall.castShadow=true;wall.receiveShadow=true;this.scene.add(wall)}}
  const towerBase=new THREE.Mesh(new THREE.BoxGeometry(30,3,18),new THREE.MeshStandardMaterial({color:0x3b3c3b,roughness:.85}));towerBase.position.set(0,-1.5,10);towerBase.castShadow=true;this.scene.add(towerBase);
  for(let x=-14;x<=14;x+=4){for(const z of [7,13]){const merlon=new THREE.Mesh(new THREE.BoxGeometry(2.5,2.6,2.5),new THREE.MeshStandardMaterial({color:0x57534b,roughness:.9}));merlon.position.set(x,1.3,z);merlon.castShadow=true;this.scene.add(merlon)}}
  for(const x of [-14,14]){const brazier=new THREE.Mesh(new THREE.CylinderGeometry(.65,.8,.7,10),new THREE.MeshStandardMaterial({color:0x282522,metalness:.25,roughness:.7}));brazier.position.set(x,3.4,9);this.scene.add(brazier);const light=new THREE.PointLight(0xff9b45,8,16);light.position.set(x,4.2,9);this.scene.add(light)}
 }
 makeTree(scale){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.18,.3,2.2,7),new THREE.MeshStandardMaterial({color:0x5a3d28}));trunk.position.y=1.1;trunk.castShadow=true;g.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.5,3.8,8),new THREE.MeshStandardMaterial({color:0x31543a,roughness:1}));crown.position.y=3.4;crown.castShadow=true;g.add(crown);g.scale.setScalar(scale);return g}
 buildWeapon(){this.weaponGroup=new THREE.Group();this.weaponGroup.position.set(.75,-.65,-1.35);this.camera.add(this.weaponGroup);this.scene.add(this.camera);this.updateWeaponModel()}
 updateWeaponModel(){this.weaponGroup.clear();const id=this.weapons.current.id;const wood=new THREE.MeshStandardMaterial({color:0x80552f,roughness:.75});const metal=new THREE.MeshStandardMaterial({color:0x2a2d30,metalness:.75,roughness:.3});if(id==='bow'){const grip=new THREE.Mesh(new THREE.CylinderGeometry(.07,.09,.65,10),wood);grip.rotation.z=Math.PI/2;this.weaponGroup.add(grip);const curve=new THREE.TorusGeometry(.52,.035,8,32,Math.PI*1.35);const bow=new THREE.Mesh(curve,wood);bow.rotation.z=-Math.PI/2;this.weaponGroup.add(bow);const string=new THREE.Mesh(new THREE.CylinderGeometry(.012,.012,1.05,6),new THREE.MeshStandardMaterial({color:0xd7c8aa}));string.rotation.z=Math.PI/2;this.weaponGroup.add(string)}else if(id.includes('crossbow')){for(let i=0;i<(id==='dual-crossbow'?2:1);i++){const g=new THREE.Group();g.position.x=i?.18:-.18;const body=new THREE.Mesh(new THREE.BoxGeometry(.8,.12,.14),wood);g.add(body);const rail=new THREE.Mesh(new THREE.BoxGeometry(.55,.045,.06),metal);rail.position.y=.08;g.add(rail);const limbs=new THREE.Mesh(new THREE.BoxGeometry(.75,.04,.38),wood);limbs.position.y=.14;g.add(limbs);this.weaponGroup.add(g)}}else{const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.24,1),new THREE.MeshStandardMaterial({color:0x777878,roughness:1}));this.weaponGroup.add(rock)}this.weaponGroup.rotation.y=-.12}
 bind(){
  window.addEventListener('keydown',e=>{if(e.key>='1'&&e.key<='4')this.select(+e.key-1);if(e.key==='a'||e.key==='ArrowLeft')this.yaw=Math.max(-Math.PI/2,this.yaw-.09);if(e.key==='d'||e.key==='ArrowRight')this.yaw=Math.min(Math.PI/2,this.yaw+.09);if(e.key==='w'||e.key==='ArrowUp')this.pitch=Math.min(.45,this.pitch+.06);if(e.key==='s'||e.key==='ArrowDown')this.pitch=Math.max(-.55,this.pitch-.06)});
  this.c.addEventListener('pointerdown',e=>{this.c.setPointerCapture?.(e.pointerId);this.pointer.down=true;this.pointer.x=e.clientX;this.pointer.y=e.clientY;this.pointer.startX=e.clientX;this.pointer.startY=e.clientY;this.pointer.moved=false});
  this.c.addEventListener('pointermove',e=>{if(!this.pointer.down)return;const dx=e.clientX-this.pointer.x,dy=e.clientY-this.pointer.y;if(Math.hypot(e.clientX-this.pointer.startX,e.clientY-this.pointer.startY)>10)this.pointer.moved=true;this.yaw=THREE.MathUtils.clamp(this.yaw-dx*.006,-Math.PI/2,Math.PI/2);this.pitch=THREE.MathUtils.clamp(this.pitch-dy*.005,-.55,.45);this.pointer.x=e.clientX;this.pointer.y=e.clientY});
  this.c.addEventListener('pointerup',e=>{const moved=this.pointer.moved;this.pointer.down=false;if(!moved)this.fireAtCrosshair()});this.c.addEventListener('pointercancel',()=>this.pointer.down=false);
 }
 select(i){this.weapons.select(i);this.updateWeaponModel();this.updateWeaponUI()}
 fireAtCrosshair(){const now=performance.now();if(!this.weapons.shoot(now))return;const weapon=this.weapons.current;this.updateCamera();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),this.camera);ray.far=weapon.range/5;const hits=ray.intersectObjects([...this.enemyMeshes.values()],true);let target=null;if(hits.length){for(const hit of hits){let obj=hit.object;while(obj&&!obj.userData.enemy)obj=obj.parent;if(obj?.userData.enemy){target=obj.userData.enemy;break}}}const end=target?new THREE.Vector3(target.x,1.05,target.z):ray.ray.origin.clone().add(ray.ray.direction.clone().multiplyScalar(Math.min(ray.far,45)));this.spawnProjectile(end,target);if(target)target.hit(weapon.damage)}
 spawnProjectile(end,target){const p=new THREE.Mesh(new THREE.SphereGeometry(.075,8,8),new THREE.MeshBasicMaterial({color:0xffd38a}));const start=this.camera.position.clone();this.scene.add(p);this.projectiles.push({mesh:p,start,end,t:0,duration:.16,target})}
 syncEnemies(){const live=new Set(this.enemies.enemies);for(const [enemy,group] of this.enemyMeshes){if(!live.has(enemy)||enemy.dead){this.scene.remove(group);this.enemyMeshes.delete(enemy)}}for(const enemy of this.enemies.enemies){if(!this.enemyMeshes.has(enemy))this.enemyMeshes.set(enemy,this.makeSlime(enemy))}}
 makeSlime(enemy){const g=new THREE.Group();g.userData.enemy=enemy;g.position.set(enemy.x,0,enemy.z);const body=new THREE.Mesh(new THREE.SphereGeometry(.85,20,14),new THREE.MeshStandardMaterial({color:0x76b86b,roughness:.65}));body.scale.y=.7;body.position.y=.75;body.castShadow=true;body.userData.enemy=enemy;g.add(body);const eyeMat=new THREE.MeshStandardMaterial({color:0x172019,roughness:.4});for(const x of [-.27,.27]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.09,10,8),eyeMat);eye.position.set(x,.88,.7);g.add(eye)}const shadow=new THREE.Mesh(new THREE.CircleGeometry(.85,24),new THREE.MeshBasicMaterial({color:0x1e2a20,transparent:true,opacity:.3}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.025;g.add(shadow);const hpBg=new THREE.Mesh(new THREE.PlaneGeometry(1.5,.11),new THREE.MeshBasicMaterial({color:0x202020,depthTest:false}));hpBg.position.y=1.8;g.add(hpBg);const hp=new THREE.Mesh(new THREE.PlaneGeometry(1.5,.09),new THREE.MeshBasicMaterial({color:0xd95c58,depthTest:false}));hp.position.set(-.75,1.8,.01);hp.scale.x=1;g.add(hp);g.userData.hp=hp;this.scene.add(g);return g}
 updateEnemyVisuals(){for(const [enemy,g] of this.enemyMeshes){g.position.set(enemy.x,0,enemy.z);g.userData.hp.scale.x=Math.max(0,enemy.hp/enemy.maxHp);g.userData.hp.position.x=-.75+(1.5*(1-enemy.hp/enemy.maxHp))/2;g.children.forEach(o=>{if(o.userData?.enemy===enemy)o.userData.enemy=enemy})}}
 update(dt){this.enemies.update(dt);this.syncEnemies();for(const e of this.enemies.enemies){if(e.z>5)this.hp=Math.max(0,this.hp-dt*14)}this.updateEnemyVisuals();for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i];p.t+=dt/p.duration;p.mesh.position.lerpVectors(p.start,p.end,Math.min(1,p.t));if(p.t>=1){this.scene.remove(p.mesh);this.projectiles.splice(i,1)}}}
 updateCamera(){this.camera.rotation.set(this.pitch,this.yaw,0)}
 resize(){const r=this.c.getBoundingClientRect();const aspect=r.width/r.height||16/9;this.camera.aspect=aspect;this.camera.updateProjectionMatrix();this.renderer.setSize(1280,720,false)}
 loop(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.updateCamera();this.update(dt);this.renderer.render(this.scene,this.camera);this.updateUI();requestAnimationFrame(x=>this.loop(x))}
 updateUI(){document.querySelector('#angle').textContent=Math.round(THREE.MathUtils.radToDeg(this.yaw))+'°';document.querySelector('#enemyCount').textContent=this.enemies.enemies.length;document.querySelector('#towerHp').style.width=this.hp+'%';document.querySelector('.top-left small').textContent=`Tower HP ${Math.ceil(this.hp)} / 100`}
 updateWeaponUI(){const bar=document.querySelector('#weaponBar');bar.innerHTML=WEAPONS.map((w,i)=>`<button class="weapon-slot ${i===this.weapons.index?'active':''}" data-index="${i}"><b>${i+1} · ${w.name}</b><small>${w.range} range · ${w.ammo===Infinity?'∞':this.weapons.ammo[i]+' ammo'}</small></button>`).join('');bar.querySelectorAll('button').forEach(b=>b.onclick=()=>this.select(+b.dataset.index))}
}
